name: Linting

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  lint-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Lint
        run: yarn run lint
  xml-linters:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Lint path
      # uses: korelstar/xmllint-problem-matcher@v1
      uses: Pattrigue/xmllint-action@v1.2
      with:
        xml-path: ./xliff/*/*.xlf